-- Migration: Scientific Lactation Module
-- Purpose: Transform Module 3 from manual livestock management to scientific comparative engine
-- Date: 2026-01-15

-- ============================================================================
-- STEP 1: Create breed_profiles table (Scientific Database)
-- ============================================================================

CREATE TABLE IF NOT EXISTS breed_profiles (
  id SERIAL PRIMARY KEY,
  breed_name VARCHAR(100) NOT NULL UNIQUE,
  breed_category VARCHAR(50) NOT NULL CHECK (breed_category IN ('dairy', 'dual_purpose', 'native')),
  
  -- Production characteristics (optimal management level)
  avg_daily_peak_liters DECIMAL(6, 2) NOT NULL, -- Peak lactation (L/day)
  peak_day INTEGER NOT NULL, -- Day of peak (typically 40-60)
  total_lactation_liters DECIMAL(10, 2) NOT NULL, -- Total per 305-day lactation
  standard_lactation_days INTEGER NOT NULL DEFAULT 305, -- Standard lactation length
  persistence_rate DECIMAL(5, 2) NOT NULL, -- % monthly decline post-peak
  
  -- Milk composition (international averages)
  fat_percentage DECIMAL(4, 2) NOT NULL,
  protein_percentage DECIMAL(4, 2) NOT NULL,
  lactose_percentage DECIMAL(4, 2) DEFAULT 4.80,
  total_solids_percentage DECIMAL(4, 2) NOT NULL,
  
  -- Reproductive cycle
  optimal_dry_period_days INTEGER DEFAULT 60,
  avg_calving_interval_days INTEGER DEFAULT 395, -- ~13 months
  
  -- Management level adjustments (multipliers)
  low_management_multiplier DECIMAL(4, 2) DEFAULT 0.70, -- 70% of optimal
  medium_management_multiplier DECIMAL(4, 2) DEFAULT 0.85, -- 85% of optimal
  high_management_multiplier DECIMAL(4, 2) DEFAULT 0.95, -- 95% of optimal
  
  -- References
  source VARCHAR(255), -- Scientific source
  region VARCHAR(100), -- Reference region
  notes TEXT,
  
  -- Metadata
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create index for faster breed lookups
CREATE INDEX IF NOT EXISTS idx_breed_profiles_name ON breed_profiles(breed_name);
CREATE INDEX IF NOT EXISTS idx_breed_profiles_category ON breed_profiles(breed_category);

-- ============================================================================
-- STEP 2: Create lactation_simulations table (Replaces lactation_data)
-- ============================================================================

CREATE TABLE IF NOT EXISTS lactation_simulations (
  id SERIAL PRIMARY KEY,
  scenario_id INTEGER NOT NULL REFERENCES scenarios(id) ON DELETE CASCADE,
  
  -- User inputs (minimal)
  selected_breed VARCHAR(100) NOT NULL,
  management_level VARCHAR(20) NOT NULL CHECK (management_level IN ('low', 'medium', 'high', 'optimal')),
  target_lactation_days INTEGER, -- NULL = use breed standard
  
  -- Calculated outputs (generated by scientific engine)
  calculated_daily_peak DECIMAL(10, 2),
  calculated_lactation_total DECIMAL(12, 2),
  calculated_persistence DECIMAL(5, 2),
  calculated_fat_kg DECIMAL(10, 2),
  calculated_protein_kg DECIMAL(10, 2),
  calculated_solids_kg DECIMAL(10, 2),
  calculated_lactose_kg DECIMAL(10, 2),
  
  -- Economic outputs
  calculated_milk_value DECIMAL(12, 2), -- Based on composition
  calculated_solids_value DECIMAL(12, 2), -- Premium for solids
  
  -- Comparison data (JSONB for flexibility)
  comparison_breeds JSONB, -- Array of compared breeds with metrics
  optimization_potential JSONB, -- Improvement opportunities
  
  -- Metadata
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(scenario_id)
);

-- Create indexes for faster queries
CREATE INDEX IF NOT EXISTS idx_lactation_simulations_scenario ON lactation_simulations(scenario_id);
CREATE INDEX IF NOT EXISTS idx_lactation_simulations_breed ON lactation_simulations(selected_breed);

-- ============================================================================
-- STEP 3: Migrate existing data (if any)
-- ============================================================================

-- Note: Existing lactation_data uses manual inputs (lactation_days, dry_days, etc.)
-- We cannot automatically convert to breed-based system, so we keep the old table
-- for backward compatibility but don't migrate data.
-- Users will need to re-enter their scenarios using the new breed selection.

-- Optionally, add a comment to old table indicating it's deprecated
COMMENT ON TABLE lactation_data IS 'DEPRECATED: Legacy manual lactation data. Use lactation_simulations with breed_profiles instead.';

-- ============================================================================
-- STEP 4: Verification queries
-- ============================================================================

-- Verify tables were created
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'breed_profiles') THEN
    RAISE NOTICE 'Table breed_profiles created successfully';
  ELSE
    RAISE EXCEPTION 'Table breed_profiles was not created';
  END IF;
  
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'lactation_simulations') THEN
    RAISE NOTICE 'Table lactation_simulations created successfully';
  ELSE
    RAISE EXCEPTION 'Table lactation_simulations was not created';
  END IF;
END $$;

-- ============================================================================
-- MIGRATION COMPLETE
-- ============================================================================
-- Next step: Run seed data script to populate breed_profiles
-- Command: npm run seed:breeds
